---
title: "Meta analysis by ratio for cardiomyocytes (5 donors cardio)"
author: "En-Hsuan Lu"
date: "2023-05-30"
output: html_document
---

```{r setup, include=FALSE}
library(metafor)
library(dplyr)
knitr::opts_chunk$set(echo = TRUE)
```
## in vivo POD

```{r read}
#original in vivo POD
origpod <- read.csv(file.path("POD database","original POD x Css for 41 chemicals.csv"))

#original in vivo POD + DAF
poddaf <- read.csv(file.path("POD database","original POD x DAF x Css for 41 chemicals.csv"))

#BBMD
BMD <- read.csv(file.path("POD database","BBMD x Css for 41 chemicals.csv"))

#HED
HED <- read.csv(file.path("POD database","HED x Css for 41 chemicals.csv"))
```

## the most sensitive in vitro POD

```{r read}
#ToxCast active
toxcast <- read.csv(file.path("POD database","41 chemicals toxcast POD.csv"))
toxcast <- toxcast[order(toxcast$Chemical),]

#cardiomyocyte single donor
cardio <- read.csv(file.path("POD database","41 chemicals cardio 5 donors POD.csv"))
```

##calculate ratio
in vitro/in vivo

```{r ratio}
#######in vitro/POD
pod.tox <- full_join(origpod, toxcast, by="Chemical")
pod.tox$tox.log10ratio <- with(pod.tox, log10(ac50.5perc/PODCss))
pod.car <- full_join(origpod, cardio, by="casn")
pod.car$car.log10ratio <- with(pod.car, log10(Min/PODCss))

#######in vitro/(POD+DAF)
poddaf.tox <- full_join(poddaf, toxcast, by="Chemical")
poddaf.tox$tox.log10ratio <- with(poddaf.tox, log10(ac50.5perc/poddaf.Css))
poddaf.car <- full_join(poddaf, cardio, by="casn")
poddaf.car$car.log10ratio <- with(poddaf.car, log10(Min/poddaf.Css))

#######in vitro/BBMD
BMD.tox <- full_join(BMD, toxcast, by="Chemical")
BMD.tox$tox.log10ratio <- with(BMD.tox, log10(ac50.5perc/BMD50.Css))
BMD.car <- full_join(BMD, cardio, by="casn")
BMD.car$car.log10ratio <- with(BMD.car, log10(Min/BMD50.Css))

#######in vitro/HED
hed.tox <- full_join(HED, toxcast, by="Chemical")
hed.tox$tox.log10ratio <- with(hed.tox, log10(ac50.5perc/HED50.Css))
hed.car <- full_join(HED, cardio, by="casn")
hed.car$car.log10ratio <- with(hed.car, log10(Min/HED50.Css))
```

##calculate standard error
#traditional POD: log10(P95/P05)=log10(100)
#BBMD/HED: log10(P95/P05)=2*1.645*se

```{r se}
pod.tox$se <- 2/(2*1.645)
pod.car$se <- 2/(2*1.645)

poddaf.tox$se <- 2/(2*1.645)
poddaf.car$se <- 2/(2*1.645)

BMD.tox$se <- with(BMD.tox, (log10(BMD95.Css/BMD5.Css))/(2*1.645))
BMD.car$se <- with(BMD.car, (log10(BMD95.Css/BMD5.Css))/(2*1.645))

hed.tox$se <- with(hed.tox, (log10(HED95.Css/HED5.Css))/(2*1.645))
hed.car$se <- with(hed.car, (log10(HED95.Css/HED5.Css))/(2*1.645))
```

##meta-analysis

```{r matefor}
pod.tox.rma <- rma(yi=tox.log10ratio, sei=se, data=pod.tox, slab=Chemical, level=90)
predict(pod.tox.rma)

pod.car.rma <- rma(yi=car.log10ratio, sei=se, data=pod.car, slab=Chemical, level=90)
predict(pod.car.rma)

poddaf.tox.rma <- rma(yi=tox.log10ratio, sei=se, data=poddaf.tox, slab=Chemical, level=90)
predict(poddaf.tox.rma)

poddaf.car.rma <- rma(yi=car.log10ratio, sei=se, data=poddaf.car, slab=Chemical, level=90)
predict(poddaf.car.rma)

bbmd.tox.rma <- rma(yi=tox.log10ratio, sei=se, data=BMD.tox, slab=Chemical, level=90)
predict(bbmd.tox.rma)

bbmd.car.rma <- rma(yi=car.log10ratio, sei=se, data=BMD.car, slab=Chemical, level=90)
predict(bbmd.car.rma)

hed.tox.rma <- rma(yi=tox.log10ratio, sei=se, data=hed.tox, slab=Chemical, level=90)
predict(hed.tox.rma)

hed.car.rma <- rma(yi=car.log10ratio, sei=se, data=hed.car, slab=Chemical, level=90)
predict(hed.car.rma)

#meta-analysis table for 41 chemicals
capture.output(pod.tox.rma, predict(pod.tox.rma), poddaf.tox.rma, predict(poddaf.tox.rma), bbmd.tox.rma, predict(bbmd.tox.rma), hed.tox.rma, predict(hed.tox.rma), file="rma log10 ToxCast to in vivo ratio for 41 chemicals (5 donors cardio).txt")
capture.output(pod.car.rma, predict(pod.car.rma), poddaf.car.rma, predict(poddaf.car.rma), bbmd.car.rma, predict(bbmd.car.rma), hed.car.rma, predict(hed.car.rma), file="rma log10 Cardiomyocytes to in vivo ratio for 41 chemicals (5 donors cardio).txt")

#BMA BMD human
#reorder by toxcast
pdf(file="meta-analysis in vitro vs BMA BMD human for 41 chemicals (5 donors cardio).pdf", width=16, height=13, pointsize=12)
par(mfrow=c(1,2))
forest(hed.tox.rma, order=hed.tox$tox.log10ratio, decreasing=TRUE, addpred = TRUE, xlab=expression("log"[10]*"(ToxCast POD/BMA BMD"[h]~"x Css)"), header="Chemicals", alim=c(-6,6))
title("A", adj = 0)
text(-12, -1, pos=4, cex=1, bquote(paste("(", I^2, " = ", .(formatC(hed.tox.rma$I2, digits=1, format="f")),  "%", ")")))
forest(hed.car.rma, order=hed.tox$tox.log10ratio, decreasing=TRUE, addpred = TRUE, xlab=expression("log"[10]*"(cardiomyocyte POD/BMA BMD"[h]~"x Css)"),  header="Chemicals", alim=c(-6,6))
title("B", adj = 0)
text(-10, -1, pos=4, cex=1, bquote(paste("(", I^2, " = ", .(formatC(hed.car.rma$I2, digits=1, format="f")),  "%", ")")))
par(mfrow = c(1, 1))
dev.off()

##supplemental plots
#reorder by toxcast
pdf(file="reorder meta-analysis in vitro vs reg POD animal for 41 chemicals (5 donors cardio).pdf", width=16, height=13, pointsize=12)
par(mfrow=c(1,2))
forest(pod.tox.rma, order=pod.tox$tox.log10ratio, decreasing=TRUE, addpred = TRUE, xlab=expression("log"[10]*"(ToxCast POD/Reg POD"[a]~"x Css)"), header="Chemicals", alim=c(-6,6))
title("A", adj = 0)
text(-12.5, -1, pos=4, cex=1, bquote(paste("(", I^2, " = ", .(formatC(pod.tox.rma$I2, digits=1, format="f")),  "%", ")")))
forest(pod.car.rma, order=pod.tox$tox.log10ratio, decreasing=TRUE, addpred = TRUE, xlab=expression("log"[10]*"(cardiomyocyte POD/Reg POD"[a]~"x Css)"),  header="Chemicals", alim=c(-6,6))
title("B", adj = 0)
text(-10.8, -1, pos=4, cex=1, bquote(paste("(", I^2, " = ",
.(formatC(pod.car.rma$I2, digits=1, format="f")),  "%", ")")))
par(mfrow = c(1, 1))
dev.off()

#regulatory POD human
#reorder by toxcast
pdf(file="reorder meta-analysis in vitro vs reg POD human for 41 chemicals (5 donors cardio).pdf", width=16, height=13, pointsize=12)
par(mfrow=c(1,2))
forest(poddaf.tox.rma, order=poddaf.tox$tox.log10ratio, decreasing=TRUE, addpred = TRUE, xlab=expression("log"[10]*"(ToxCast POD/Reg POD"[h]~"x Css)"), header="Chemicals", alim=c(-6,6))
title("A", adj = 0)
text(-11.7, -1, pos=4, cex=1, bquote(paste("(", I^2, " = ", .(formatC(poddaf.tox.rma$I2, digits=1, format="f")),  "%", ")")))
forest(poddaf.car.rma, order=poddaf.tox$tox.log10ratio, decreasing=TRUE, addpred = TRUE, xlab=expression("log"[10]*"(cardiomyocyte POD/Reg POD"[h]~"x Css)"),  header="Chemicals", alim=c(-6,6))
title("B", adj = 0)
text(-9.7, -1, pos=4, cex=1, bquote(paste("(", I^2, " = ", .(formatC(poddaf.car.rma$I2, digits=1, format="f")),  "%", ")")))
par(mfrow = c(1, 1))
dev.off()

#BMA BMD animal
#reorder by toxcast
pdf(file="reorder meta-analysis in vitro vs BMA BMD animal for 41 chemicals (5 donors cardio).pdf", width=16, height=13, pointsize=12)
par(mfrow=c(1,2))
forest(bbmd.tox.rma, order=BMD.tox$tox.log10ratio, decreasing=TRUE, addpred = TRUE, xlab=expression("log"[10]*"(ToxCast POD/BMA BMD"[a]~"x Css)"), header="Chemicals", alim=c(-6,6))
title("A", adj = 0)
text(-12.4, -1, pos=4, cex=1, bquote(paste("(", I^2, " = ", .(formatC(bbmd.tox.rma$I2, digits=1, format="f")),  "%", ")")))
forest(bbmd.car.rma, order=BMD.tox$tox.log10ratio, decreasing=TRUE, addpred = TRUE, xlab=expression("log"[10]*"(cardiomyocyte POD/BMA BMD"[a]~"x Css)"),  header="Chemicals", alim=c(-6,6))
title("B", adj = 0)
text(-10.4, -1, pos=4, cex=1, bquote(paste("(", I^2, " = ",
.(formatC(bbmd.car.rma$I2, digits=1, format="f")),  "%", ")")))
par(mfrow = c(1, 1))
dev.off()
```
